"""Stream type classes for tap-ttd."""

from __future__ import annotations

import typing as t
from importlib import resources
import io
import time
from singer_sdk import typing as th  # JSON Schema typing helpers

from tap_ttd.client import ttdStream
import csv
import jsonschema
from jsonschema import validate
import requests
from singer_sdk.typing import PropertiesList, Property, StringType, IntegerType, NumberType
from googleapiclient.http import MediaIoBaseDownload
class StandardStream(ttdStream):
    """Define custom stream."""
    name = "standard_streams"
    primary_keys: t.ClassVar[list[str]] = ["id"]
    path = "https://api.thetradedesk.com"

    schema = PropertiesList(
        Property("Date", StringType, description="The date of the record."),
        Property("Partner ID", StringType, description="The ID of the partner."),
        Property("Advertiser ID", StringType, description="The ID of the advertiser."),
        Property("Campaign ID", StringType, description="The ID of the campaign."),
        Property("Ad Group ID", StringType, description="The ID of the ad group."),
        Property("Ad Format", StringType, description="The format of the ad."),
        Property("Creative ID", StringType, description="The ID of the creative."),
        Property("Frequency", StringType, description="The frequency of the ad."),
        Property("Advertiser", StringType, description="The name of the advertiser."),
        Property("Campaign", StringType, description="The name of the campaign."),
        Property("Ad Group", StringType, description="The name of the ad group."),
        Property("Ad Group Budget In Impressions", StringType, description="Budget in impressions for the ad group."),
        Property("Ad Group Daily Cap In Impressions", StringType, description="Daily cap in impressions for the ad group."),
        Property("Ad Group Daily Target In Impressions", StringType, description="Daily target in impressions for the ad group."),
        Property("Ad Group Base Bid CPM (Adv Currency)", StringType, description="Base bid CPM in advertiser currency."),
        Property("Ad Group Budget (Adv Currency)", StringType, description="Budget in advertiser currency."),
        Property("Ad Group Daily Cap (Adv Currency)", StringType, description="Daily cap in advertiser currency."),
        Property("Ad Group Daily Target (Adv Currency)", StringType, description="Daily target in advertiser currency."),
        Property("Advertiser Currency Code", StringType, description="Currency code for the advertiser."),
        Property("Partner Currency Code", StringType, description="Currency code for the partner."),
        Property("Creative", StringType, description="The name of the creative."),
        Property("01 - Click Conversion Currency", StringType, description="The currency for the first click conversion."),
        Property("01 - View Through Conversion Currency", StringType, description="The currency for the first view-through conversion."),
        Property("02 - Click Conversion Currency", StringType, description="The currency for the second click conversion."),
        Property("02 - View Through Conversion Currency", StringType, description="The currency for the second view-through conversion."),
        Property("03 - Click Conversion Currency", StringType, description="The currency for the third click conversion."),
        Property("03 - View Through Conversion Currency", StringType, description="The currency for the third view-through conversion."),
        Property("04 - Click Conversion Currency", StringType, description="The currency for the fourth click conversion."),
        Property("04 - View Through Conversion Currency", StringType, description="The currency for the fourth view-through conversion."),
        Property("05 - Click Conversion Currency", StringType, description="The currency for the fifth click conversion."),
        Property("05 - View Through Conversion Currency", StringType, description="The currency for the fifth view-through conversion."),
        Property("06 - Click Conversion Currency", StringType, description="The currency for the sixth click conversion."),
        Property("06 - View Through Conversion Currency", StringType, description="The currency for the sixth view-through conversion."),
        Property("Deal ID", StringType, description="The ID of the deal."),
        Property("Ad Server Name", StringType, description="The name of the ad server."),
        Property("Ad Server Creative Placement ID", StringType, description="The creative placement ID in the ad server."),
        Property("Bids", StringType, description="The total number of bids."),
        Property("Total Bid Amount (Adv Currency)", StringType, description="Total bid amount in advertiser currency."),
        Property("Total Bid Amount (Partner Currency)", StringType, description="Total bid amount in partner currency."),
        Property("Total Bid Amount (USD)", StringType, description="Total bid amount in USD."),
        Property("Impressions", StringType, description="The total number of impressions."),
        Property("Clicks", StringType, description="The total number of clicks."),
        Property("TTD Cost (Adv Currency)", StringType, description="The cost in advertiser currency."),
        Property("TTD Cost (Partner Currency)", StringType, description="The cost in partner currency."),
        Property("TTD Cost (USD)", StringType, description="The cost in USD."),
        Property("Partner Cost (Adv Currency)", StringType, description="Partner cost in advertiser currency."),
        Property("Partner Cost (Partner Currency)", StringType, description="Partner cost in partner currency."),
        Property("Partner Cost (USD)", StringType, description="Partner cost in USD."),
        Property("Advertiser Cost (Adv Currency)", StringType, description="Advertiser cost in advertiser currency."),
        Property("Advertiser Cost (Partner Currency)", StringType, description="Advertiser cost in partner currency."),
        Property("Advertiser Cost (USD)", StringType, description="Advertiser cost in USD."),
        Property("Player Views", StringType, description="Number of player views."),
        Property("Player Starts", StringType, description="Number of player starts."),
        Property("Player 25% Complete", StringType, description="Number of 25% completions."),
        Property("Player 50% Complete", StringType, description="Number of 50% completions."),
        Property("Player 75% Complete", StringType, description="Number of 75% completions."),
        Property("Player Completed Views", StringType, description="Number of completed views."),
        Property("Player Mute", StringType, description="Number of mute actions."),
        Property("Player Unmute", StringType, description="Number of unmute actions."),
        Property("Player Pause", StringType, description="Number of pause actions."),
        Property("Player Resume", StringType, description="Number of resume actions."),
        Property("Player Full Screen", StringType, description="Number of fullscreen actions."),
        Property("Player Errors", StringType, description="Number of errors."),
        Property("Player Skip", StringType, description="Number of skip actions."),
        Property("Player Engaged Views", StringType, description="Number of engaged views."),
        Property("Player Rewind", StringType, description="Number of rewind actions."),
        Property("Player Expansion", StringType, description="Number of expansions."),
        Property("Player Collapse", StringType, description="Number of collapses."),
        Property("Player Invitation Accept", StringType, description="Number of invitation accepts."),
        Property("Player Close", StringType, description="Number of close actions."),
        Property("Sampled Tracked Impressions", StringType, description="Sampled tracked impressions."),
        Property("Sampled Viewed Impressions", StringType, description="Sampled viewed impressions."),
        Property("01 - Conversion Touch", StringType, description="The first conversion touch."),
        Property("01 - Conversion Touch Revenue", StringType, description="Revenue for the first conversion touch."),
        Property("01 - Click Conversion", StringType, description="The first click conversion."),
        Property("01 - Click Conversion Revenue", StringType, description="Revenue for the first click conversion."),
        Property("01 - View Through Conversion", StringType, description="The first view-through conversion."),
        Property("01 - View Through Conversion Revenue", StringType, description="Revenue for the first view-through conversion."),
        Property("01 - Time Weighted Decay Conversion", StringType, description="The first time-weighted decay conversion."),
        Property("01 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the first time-weighted decay conversion."),
        Property("02 - Time Weighted Decay Conversion", StringType, description="The second time-weighted decay conversion."),
        Property("02 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the second time-weighted decay conversion."),
        Property("02 - View Through Conversion", StringType, description="The second view-through conversion."),
        Property("02 - View Through Conversion Revenue", StringType, description="Revenue for the second view-through conversion."),
        Property("02 - Click Conversion", StringType, description="The second click conversion."),
        Property("02 - Click Conversion Revenue", StringType, description="Revenue for the second click conversion."),
        Property("02 - Conversion Touch", StringType, description="The second conversion touch."),
        Property("02 - Conversion Touch Revenue", StringType, description="Revenue for the second conversion touch."),
        Property("03 - Conversion Touch", StringType, description="The third conversion touch."),
        Property("03 - Conversion Touch Revenue", StringType, description="Revenue for the third conversion touch."),
        Property("03 - Click Conversion", StringType, description="The third click conversion."),
        Property("03 - Click Conversion Revenue", StringType, description="Revenue for the third click conversion."),
        Property("03 - View Through Conversion", StringType, description="The third view-through conversion."),
        Property("03 - View Through Conversion Revenue", StringType, description="Revenue for the third view-through conversion."),
        Property("03 - Time Weighted Decay Conversion", StringType, description="The third time-weighted decay conversion."),
        Property("03 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the third time-weighted decay conversion."),
        Property("04 - Time Weighted Decay Conversion", StringType, description="The fourth time-weighted decay conversion."),
        Property("04 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the fourth time-weighted decay conversion."),
        Property("04 - View Through Conversion", StringType, description="The fourth view-through conversion."),
        Property("04 - View Through Conversion Revenue", StringType, description="Revenue for the fourth view-through conversion."),
        Property("04 - Click Conversion", StringType, description="The fourth click conversion."),
        Property("04 - Click Conversion Revenue", StringType, description="Revenue for the fourth click conversion."),
        Property("04 - Conversion Touch", StringType, description="The fourth conversion touch."),
        Property("04 - Conversion Touch Revenue", StringType, description="Revenue for the fourth conversion touch."),
        Property("05 - Conversion Touch", StringType, description="The fifth conversion touch."),
        Property("05 - Conversion Touch Revenue", StringType, description="Revenue for the fifth conversion touch."),
        Property("05 - Click Conversion", StringType, description="The fifth click conversion."),
        Property("05 - Click Conversion Revenue", StringType, description="Revenue for the fifth click conversion."),
        Property("05 - View Through Conversion", StringType, description="The fifth view-through conversion."),
        Property("05 - View Through Conversion Revenue", StringType, description="Revenue for the fifth view-through conversion."),
        Property("05 - Time Weighted Decay Conversion", StringType, description="The fifth time-weighted decay conversion."),
        Property("05 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the fifth time-weighted decay conversion."),
        Property("06 - Time Weighted Decay Conversion", StringType, description="The sixth time-weighted decay conversion."),
        Property("06 - Time Weighted Decay Conversion Revenue", StringType, description="Revenue for the sixth time-weighted decay conversion."),
        Property("06 - Conversion Touch", StringType, description="The sixth conversion touch."),
        Property("06 - Conversion Touch Revenue", StringType, description="Revenue for the sixth conversion touch."),
        Property("06 - Click Conversion", StringType, description="The sixth click conversion."),
        Property("06 - Click Conversion Revenue", StringType, description="Revenue for the sixth click conversion."),
        Property("06 - View Through Conversion", StringType, description="The sixth view-through conversion."),
        Property("06 - View Through Conversion Revenue", StringType, description="Revenue for the sixth view-through conversion."),
    ).to_dict()

